config/routes.rb
Rails.application.routes.draw do

  resources :session_infos
  resources :session_attendances
  resources :project_weeklies
  resources :project_meetings
  resources :project_profiles
  resources :archives
  resources :users
  root 'archives#index'
  get 'archives/new' => 'archives#new'

  post 'getSessionAttendanceArray' => 'users#getSessionAttendanceArray'
  get 'check_duplicates' => 'users#check_duplicates'
  get 'penaltyRanking' => 'users#penaltyRanking'
  post 'authenticate' => 'authentication#authenticate'
  post 'getProjectMember' => 'users#getProjectMember'

end

app/models/archive.rb
class Archive < ApplicationRecord
  mount_uploader :attachment, AttachmentUploader
end

app/controllers/archives_controller.rb
class ArchivesController < ApplicationController
  before_action :set_archive, only: [:show, :update, :destroy]

  # GET /archives
  def index
    @archives = Archive.all

    render json: @archives
  end

  # GET /archives/1
  def show
    render json: @archive
  end

  # POST /archives
  def create
    @archive = Archive.new(archive_params)

    if @archive.save
      render json: @archive, status: :created, location: @archive
    else
      render json: @archive.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /archives/1
  def update
    if @archive.update(archive_params)
      render json: @archive
    else
      render json: @archive.errors, status: :unprocessable_entity
    end
  end

  # DELETE /archives/1
  def destroy
    @archive.destroy
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_archive
      @archive = Archive.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def archive_params
      params.require(:archive).permit(:archive_title, :archive_content, :archive_upload_at, :attachment)
    end
end

app/views/archives/_form.html.erb
<%= form_for(@archive) do |f| %>
  <% if @archive.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@archive.errors.count, "error") %> prohibited this archive from being saved:</h2>

      <ul>
      <% @archive.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_field :content %>
  </div>
  <div class="field">
    <%= f.label :attachment %><br>
    <%= f.file_field :attachment %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/archives/edit.html.erb
<h1>Editing Archive</h1>

<%= render 'form' %>

<%= link_to 'Show', @archive %> |
<%= link_to 'Back', archives_path %>

app/views/archives/index.html.erb
<p id="notice"><%= notice %></p>

<%= current_user.email%>님 환영합니다.
<a href="/users/sign_out" data-method="delete">로그아웃</a> <!-- 로그아웃 기능  -->

<h1>Listing Archives</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>Attachment</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @archives.each do |archive| %>
      <tr>
        <td><%= archive.title %></td>
        <td><%= archive.content %></td>
        <td><%= archive.attachment %></td>
        <td><%= link_to 'Show', archive %></td>
        <td><%= link_to 'Edit', edit_archive_path(archive) %></td>
        <td><%= link_to 'Destroy', archive, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Archive', new_archive_path %>

app/views/archives/new.html.erb
<h1>New Archive</h1>

<%= render 'form' %>

<%= link_to 'Back', archives_path %>

app/views/archives/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @archive.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @archive.content %>
</p>

<p>
  <strong>Attachment:</strong>
  <%= @archive.attachment %>
</p>

<%= link_to 'Edit', edit_archive_path(@archive) %> |
<%= link_to 'Back', archives_path %>